export type EmailDataProps = (typeof EMAILS)[0]

export const EMAILS = [
  {
    id: "1",
    name: "Andy",
    avatar: "https://mighty.tools/mockmind-api/content/human/44.jpg",
    marker: "importante",
    subject: "What is Lorem Ipsum",
    message:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    star: false,
    date: "12 de fev.",
  },
  {
    id: "2",
    name: "John",
    avatar: "https://mighty.tools/mockmind-api/content/human/65.jpg",
    marker: "importante",
    subject: "Where does it come from",
    message:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the  source. ",
    star: true,
    date: "13 de fev.",
  },
  {
    id: "3",
    name: "Stackoverflow",
    avatar: "https://mighty.tools/mockmind-api/content/human/55.jpg",
    marker: "",
    subject: "The Overflow #69: When internal devs are your customers",
    message: "Welcome to ISSUE #69 of the Overflow! This newsletter is by developers, for developers, written and curated by the Stack Overflow team and Cassidy Williams at Netlify. Our menu this week: branch out with Git, fade to black in old video games, and prevent code injection in JavaScript and Node.",
    star: false,
    date: "24 de jan.",
  },
  {
    id: "4",
    name: "Adam Wathan",
    avatar: "https://mighty.tools/mockmind-api/content/human/45.jpg",
    marker: "",
    subject: "Tailwind UI Update: React + Vue support is here!",
    message: "Hey folks, two big updates for you today! 🥳 First of all, React + Vue support for Tailwind UI is now available! Every single component can be copied as a fully functional, fully accessible React or Vue example, and easily dropped directly into your project.",
    star: true,
    date: "05 de jan.",
  },
  {
    id: "5",
    name: "Visa",
    avatar: "https://mighty.tools/mockmind-api/content/human/62.jpg",
    marker: "",
    subject: "Coming soon: an easier way to verify you on Click to Pay with Visa",
    message: "We take the security of your Visa card information very seriously. That's why we're rolling out an easier way to verify it's you. When you make a payment with Click to Pay, we currently send you a verification code via email. To make this even more accessible and convenient we may now also be sending this code by SMS. Message and data rates may apply.",
    star: false,
    date: "01 de jan.",
  },
  {
    id: "6",
    name: "Adam Wathan",
    avatar: "https://mighty.tools/mockmind-api/content/human/45.jpg",
    marker: "",
    subject: "Tailwind UI Update: React + Vue support is here!",
    message: "Hey folks, two big updates for you today! 🥳 First of all, React + Vue support for Tailwind UI is now available! Every single component can be copied as a fully functional, fully accessible React or Vue example, and easily dropped directly into your project.",
    star: true,
    date: "05 de jan.",
  },
  {
    id: "7",
    name: "Visa",
    avatar: "https://mighty.tools/mockmind-api/content/human/62.jpg",
    marker: "",
    subject: "Coming soon: an easier way to verify you on Click to Pay with Visa",
    message: "We take the security of your Visa card information very seriously. That's why we're rolling out an easier way to verify it's you. When you make a payment with Click to Pay, we currently send you a verification code via email. To make this even more accessible and convenient we may now also be sending this code by SMS. Message and data rates may apply.",
    star: false,
    date: "01 de jan.",
  },
  {
    id: "8",
    name: "Stackoverflow",
    avatar: "https://mighty.tools/mockmind-api/content/human/55.jpg",
    marker: "",
    subject: "The Overflow #69: When internal devs are your customers",
    message: "Welcome to ISSUE #69 of the Overflow! This newsletter is by developers, for developers, written and curated by the Stack Overflow team and Cassidy Williams at Netlify. Our menu this week: branch out with Git, fade to black in old video games, and prevent code injection in JavaScript and Node.",
    star: false,
    date: "24 de jan.",
  },
]